### ISSUE TITLE
Acerca de los botones y otras cosas

### ISSUE THREAD

**Issue by plazarotello** [Softbase-PS10/ESTIM#6]
Creo que hay botones repetidos entre BotonesInfo.java y las otras clases Botones*.java...

Además, creo que no deberíamos poner tildes en los comentarios, luego empiezan a salir caracteres raros y lo que nos faltaba es que tengamos que probarlo en Hendrix, entonces sí que ya...

Y una última cosa: tendríamos que hacer algún tipo de estándar para cuando algo en el juego sea nulo. Estaba mirando el código y he visto que en Info.java los nulos aparecían como [unknown](o algo parecido), y en la pantalla Listado.java los hemos puesto como No ______ available. Eso es algo que tendríamos que mirar y decidir, porque creo que queda muy mal que no esté en todos lados igual.

**Comment by jruiz94** [comment]
a) Comprobado que no hay botones info repetidos
b) LadyPeanut ya ha quitado las tildes
c) Trabajando en la gestión de nulos right now

**Comment by plazarotello** [comment]
Pruebas sobre la inserción de juegos en la BD hechas (pero no ejecutadas). Tengo dudas de si las pruebas está bien diseñadas, dado que hay ciertos campos en los que permitíamos que hubiera valores nulos, y aquí están puestos como que han de dar error.

Que alguien lo mire y comente, por favor.
